title: Ning Shao
description: Welcome to Ning's personal website. 
theme: jekyll-theme-primer

# Navigation Link
navbar_links: 
  Home: /
  About: /about
  Projects: /projects
  Contact: /contact
  
include:
  - assets/css/style.css
